#!/bin/bash
# customize-toolkit.sh
# Quick script to customize the Community Cleanup Toolkit for your own cleanup event.
# Run this after forking the repo to personalize all templates and the website.
#
# Usage: ./scripts/customize-toolkit.sh
#
# Part of the Community Cleanup Toolkit
# https://github.com/ai-village-agents/community-cleanup-toolkit

set -e

echo "🌿 Community Cleanup Toolkit — Customization Script"
echo "===================================================="
echo ""
echo "This script will help you customize the toolkit for your cleanup event."
echo "Press Ctrl+C at any time to cancel."
echo ""

# Gather information
read -p "📍 Park/Location name: " PARK_NAME
read -p "🏙️  City and State (e.g., 'Brooklyn, NY'): " CITY_STATE
read -p "📅 Cleanup date (e.g., 'March 15, 2026'): " CLEANUP_DATE
read -p "⏰ Start time (e.g., '10:00 AM'): " START_TIME
read -p "⏰ End time (e.g., '12:00 PM'): " END_TIME
read -p "👤 Organizer name: " ORGANIZER_NAME
read -p "📧 Contact email: " CONTACT_EMAIL
read -p "🔗 Signup form URL (leave blank if not yet created): " SIGNUP_URL

echo ""
echo "📝 Summary:"
echo "   Location:  $PARK_NAME, $CITY_STATE"
echo "   Date/Time: $CLEANUP_DATE, $START_TIME - $END_TIME"
echo "   Organizer: $ORGANIZER_NAME ($CONTACT_EMAIL)"
if [ -n "$SIGNUP_URL" ]; then
    echo "   Signup:    $SIGNUP_URL"
fi
echo ""
read -p "Does this look correct? (y/n): " CONFIRM

if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "Y" ]; then
    echo "Cancelled. Run the script again to start over."
    exit 0
fi

echo ""
echo "🔧 Customizing templates..."

# Create a customization info file
cat > CLEANUP_INFO.md << EOF
# Your Cleanup Event

| Detail | Value |
|--------|-------|
| **Location** | $PARK_NAME, $CITY_STATE |
| **Date** | $CLEANUP_DATE |
| **Time** | $START_TIME - $END_TIME |
| **Organizer** | $ORGANIZER_NAME |
| **Contact** | $CONTACT_EMAIL |
| **Signup URL** | ${SIGNUP_URL:-Not yet created} |

## Next Steps

1. ✅ Customization info saved
2. 📋 Review templates in \`templates/\` and fill in your event details
3. 📖 Read through guides in \`guides/\` for planning help
4. 🌐 Update \`docs/index.html\` with your park name and photos
5. 📣 Use the outreach templates to spread the word!

*Generated by customize-toolkit.sh on $(date)*
EOF

echo "   ✅ Created CLEANUP_INFO.md with your event details"

# Update outreach templates with event info
if [ -f "templates/outreach-templates.md" ]; then
    sed -i "s/\[Park Name\]/$PARK_NAME/g" templates/outreach-templates.md 2>/dev/null || true
    sed -i "s/\[City\]/$CITY_STATE/g" templates/outreach-templates.md 2>/dev/null || true
    sed -i "s/\[Date\]/$CLEANUP_DATE/g" templates/outreach-templates.md 2>/dev/null || true
    sed -i "s/\[Time\]/$START_TIME - $END_TIME/g" templates/outreach-templates.md 2>/dev/null || true
    echo "   ✅ Updated outreach templates with event details"
fi

echo ""
echo "🎉 Customization complete!"
echo ""
echo "Next steps:"
echo "  1. Review CLEANUP_INFO.md for a summary"
echo "  2. Check templates/ — some placeholders may still need manual editing"
echo "  3. Update docs/index.html with your park name and remove Devoe Park examples"
echo "  4. Commit your changes: git add -A && git commit -m 'Customize for $PARK_NAME cleanup'"
echo "  5. Push to your fork: git push"
echo ""
echo "Good luck with your cleanup! 🌿"
